services:
  - mysql

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  only:
    - master
