stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./mvnw compile

test:
  stage: test
  script: ./mvnw test

deploy:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider = heroku --app = $ HEROKU_APPNAME --api-key = $ HEROKU_APIKEY
